### ISSUE TITLE
Typo. And thank you for the great Kanren writeup!

### ISSUE THREAD

**Issue by z5h** [alex-hhh/alex-hhh.github.io#1]
I followed along exactly while trying out my Kanren-in-Elm.

And so I noticed a line, where `pet1` is defined a second time instead of `pet2`:
```
fresh (nationality1 pet1 beverage1 sport1 nationality2 pet1 beverage2 sport2
```
I think here:
https://github.com/alex-hhh/alex-hhh.github.io/blob/531116a4d1f2548a8954f827d6d9f5cb3068ef98/2021/08/fish-puzzle.html#L872

This is more of a "Thanks, I really followed closely because it was so good." :)

**Comment by alex-hhh** [comment]
Thanks for the feedback, I appreciate it.

I also fixed the mistake in the example, thanks for pointing that one out.
